# Generated by Django 4.2.2 on 2024-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_donation_tg_chat_id_remove_user_tg_nick_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Укажите telegram-ник",
                max_length=50,
                null=True,
                verbose_name="Tg name",
            ),
        ),
    ]
