# Generated by Django 4.2.2 on 2024-07-30 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dogs", "0002_breed_owner_dog_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="like",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите лайки",
                null=True,
                related_name="user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
