# Generated by Django 4.2.2 on 2024-07-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_dog_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dog",
            old_name="like",
            new_name="likes",
        ),
    ]
